name: Rust

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

    - name: Install rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

    - name: Build the executable
      run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

    - name: Copy files in target to root
      run: cp target/x86_64-pc-windows-gnu/release/arti-facts.exe arti-facts.exe && cp target/x86_64-unknown-linux-musl/release/arti-facts arti-facts

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["arti-facts.exe", "arti-facts"]'
